import { Inter } from "next/font/google";
import "../globals.css";
import * as React from "react";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/AuthContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Removed localhost script for production */}
      </head>
      <body
        className={` mx-auto max-w-[24400px] hide-scrollbar overflow-x-hidden overflow-y-hidden`}
      >
        <AuthProvider>
          {children}
          <Toaster />
          </AuthProvider>

      </body>
    </html>
  );
}
